CREATE TABLE job_application (
	id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_name    VARCHAR(255) NOT NULL,
	job_title       VARCHAR(255) NOT NULL,
	job_description TEXT,
	status          VARCHAR(20) NOT NULL,
	match_score     INTEGER,
	cover_letter    TEXT,
	created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
	updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT job_application_status_check
		CHECK (status IN ('SAVED', 'APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED'))
);
