CREATE TABLE users (
	id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email         VARCHAR(255) NOT NULL,
	password_hash VARCHAR(100) NOT NULL,
	created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT users_email_unique UNIQUE (email)
);

-- Rows created before login existed have no owner. They were test data, so they are removed.
DELETE FROM job_application;
DELETE FROM resume;

-- Every resume and job application now belongs to one user. Deleting a user deletes their data.
ALTER TABLE resume
	ADD COLUMN user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE job_application
	ADD COLUMN user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE;

CREATE INDEX resume_user_id_idx ON resume (user_id);
CREATE INDEX job_application_user_id_idx ON job_application (user_id);
