-- The latest full AI analysis of each job application (one row per application)
CREATE TABLE match_analysis (
	id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	application_id  BIGINT NOT NULL REFERENCES job_application (id) ON DELETE CASCADE,
	resume_id       BIGINT REFERENCES resume (id) ON DELETE SET NULL,
	match_score     INTEGER NOT NULL,
	-- The three lists are stored as JSON arrays, e.g. ["Java","Docker"]
	matching_skills TEXT NOT NULL,
	missing_skills  TEXT NOT NULL,
	resume_tips     TEXT NOT NULL,
	model_name      VARCHAR(100) NOT NULL,
	analyzed_at     TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT match_analysis_application_unique UNIQUE (application_id)
);
