-- An optional name, used for the greeting on the dashboard
ALTER TABLE users
	ADD COLUMN name VARCHAR(100);

-- Notes, an optional interview date, the tone of the stored cover letter,
-- and the moment the application got its current status ("days in this stage")
ALTER TABLE job_application
	ADD COLUMN notes TEXT,
	ADD COLUMN interview_at TIMESTAMP WITH TIME ZONE,
	ADD COLUMN cover_letter_tone VARCHAR(20),
	ADD COLUMN status_changed_at TIMESTAMP WITH TIME ZONE;

UPDATE job_application
SET status_changed_at = CASE WHEN status = 'SAVED' THEN created_at ELSE updated_at END;

ALTER TABLE job_application
	ALTER COLUMN status_changed_at SET NOT NULL;

-- Every status change of an application, with its date. The first row of an application has no "from".
CREATE TABLE application_status_history (
	id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	application_id BIGINT NOT NULL REFERENCES job_application (id) ON DELETE CASCADE,
	from_status    VARCHAR(20),
	to_status      VARCHAR(20) NOT NULL,
	changed_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX application_status_history_application_idx ON application_status_history (application_id, changed_at);

-- Applications that existed before this table: what is known is when they were created and what they are now.
-- The steps in between were not recorded, so they are not invented here.
INSERT INTO application_status_history (application_id, from_status, to_status, changed_at)
SELECT id, NULL, 'SAVED', created_at
FROM job_application;

INSERT INTO application_status_history (application_id, from_status, to_status, changed_at)
SELECT id, 'SAVED', status, updated_at
FROM job_application
WHERE status <> 'SAVED';

-- The uploaded PDF itself, kept apart from the resume row so that listing resumes never loads the files
CREATE TABLE resume_file (
	resume_id BIGINT PRIMARY KEY REFERENCES resume (id) ON DELETE CASCADE,
	data      BYTEA NOT NULL
);

ALTER TABLE resume
	ADD COLUMN has_file BOOLEAN NOT NULL DEFAULT FALSE;
